Include `load` in docs
bazelbuild/stardoc pull request #216
Opened 2024-04-27 22:29 UTC by fmeum

Rules, providers, functions and aspects now have a small `load` statement in their summary. Aspects additionally include a copyable `--aspects` flag.

2024-04-27 22:56 UTC, fmeum commented
Some tests are failing due to differing repository names. I can look into this when there is general consensus on the approach.

2024-05-20 16:07 UTC, tetromino requested changes
Looks good! I updated the branch after the recent churn, which hopefully should fix test failures.

One nit: I would put a blank line between `load(...)` and the usage of the symbol, as in buildifier-formatted output.

2024-05-21 16:05 UTC, fmeum commented on src/main/java/com/google/devtools/build/stardoc/rendering/MarkdownUtil.java
I did that. I got rid of the aspect flag comment as it feels to niche.

2024-05-21 16:14 UTC, fmeum commented
The WORKSPACE tests are failing since they use a different repo name for Stardoc, which now appears in `load` statements. How do you want me to deal with that?

2024-06-18 14:59 UTC, tetromino commented
> The WORKSPACE tests are failing since they use a different repo name for Stardoc, which now appears in `load` statements. How do you want me to deal with that?

Excellent question! We may have to tag those tests "manual" + bazel version for which the golden was generated; in #232, I am adding a way to auto-update tests whose goldens are valid only for a particular Bazel release.

2024-06-18 15:20 UTC, fmeum commented
I'll wait for #232 then, let me know what I need to do after it has been merged.

2024-06-18 20:28 UTC, tetromino approved these changes
LGTM.

I took the liberty to fix up the tests, since the merge + necessary tagging and bazelci setup is a bit tricky.

2024-06-18 20:34 UTC, merged