Merge user-defined tags with default tags in stardoc macro
bazelbuild/stardoc pull request #247
Opened 2024-08-03 20:58 UTC by yashathwani

### Description

This pull request introduces changes to the `stardoc` macro to enhance its functionality by including user-defined tags in auxiliary targets. Previously, auxiliary targets only included default tags, and there was no way to specify additional tags.

### Changes Made

1. **Tag Handling:**
   - **Update:** Modified the `stardoc` macro to merge user-defined tags with default tags for auxiliary targets.
   - **Default Behavior:** By default, auxiliary targets receive the `["manual"]` tag.
   - **User-defined Tags:** If user-defined tags are provided, they are appended to the default tag list.

2. **Code Modifications:**
   - **File Updated:** `stardoc/stardoc.bzl`
   - **Details:** Added logic to handle the merging of tags in the `stardoc` macro. Ensured that user-defined tags are correctly 
     combined with default tags before being applied to auxiliary targets.

2024-08-05 21:02 UTC, tetromino requested changes
What if kwargs["tags"] already contains "manual"? In that case, you don't want to add the tag lists - it's good style to avoid duplicate tags.

2024-08-06 09:30 UTC, yashathwani commented
@tetromino @evan-flynn-apexai I have made the requested changes please have a look !!

2024-08-06 14:18 UTC, tetromino requested changes
This merging algorithm is worst-case O(n^2) where n = len(kwargs["tags"]).

Please use a linear-time algorithm.

2024-08-06 20:38 UTC, tetromino requested changes
Better! But this version hard-codes the default content of auxiliary_targets_kwargs["tags"] in two places: lines 93 and 97.

Instead, you can do something like

```bzl
auxiliary_target_kwargs["tags"] += [tag for tag in user_tags if tag not in auxiliary_target_kwargs["tags"]]
````

(Note that the above is *not* quadratic in len(user_tags) because it doesn't modify auxiliary_target_kwargs["tags"] until the final step.)

2024-08-06 23:50 UTC, yashathwani commented
@tetromino Thank you for your feedback on the tag merging logic. I've implemented your suggestion to merge the tags from kwargs without duplicating "manual" and pushed the changes.Please let me know if there are any further adjustments needed.

2024-08-07 14:42 UTC, tetromino approved these changes
Thanks!

2024-08-07 14:44 UTC, merged